### PR TITLE
AB#90619 Merge MIP and WARP scripts PR

### PR DESCRIPTION
**Pull request by glennl-msft**
replaced GenerateWAFReport.ps1 with updated version
replaced supporting files needed by GenerateWAFReports.ps1
added waf,json
removed wasa.json
updated PnP-DevOps.ps1 & PnP-Github.ps1 replacing instances of wasa.json with waf.json

### CODE REVIEW

**Comment by JoeyBarnes** [comment]
Hi Glenn - I was going thru the PRs and I had merged a previous PR that appears to be conflicting with yours.  Another contributor had made some changes to the GenerateWAFReport.ps1.  Can you take a peek at those conflicts and see if it breaks your changes?

**Comment by glennl-msft** [comment]
@JoeyBarnes resolve conflicts button for me is greyed out.  is there another way to review the conflicts on github with the access level I have?

**Review by rspott — APPROVED** [review]

**Comment by JoeyBarnes** [comment]
@glennl-msft - Did Tristan's changes in his PR include all your changes?  If so, I am just going to close this PR

**Comment by glennl-msft** [comment]
> @glennl-msft - Did Tristan's changes in his PR include all your changes? If so, I am just going to close this PR

@JoeyBarnes Tristan's PR replaces mine.  So please reject this PR and consider Tristan's PR for approval and merge.

**Pull request closed without merging**
